name: TradeCore
version: '${version}'
main: net.riblab.tradecore.TradeCore
api-version: "1.20"
depend:
  - Vault
  - ProtocolLib
  - UltimateAdvancementAPI
  - FastAsyncWorldEdit
  - CommandAPI
  - NBTAPI
  - ConfigLib
softdepend:
  - WorldGuard